import { Express, Request, Response } from "express";
import swaggerJsdoc from "swagger-jsdoc";
import swaggerUi from "swagger-ui-express";

import { version } from "../../../../package.json";

const options = {
  throwErrorOnUnsupported: true,
  swaggerDefinition: {
    openapi: "3.0.0",
    info: {
      title: "Test API",
      version: version,
      description: "Test Express API with autogenerated swagger doc",
    },
  },
  apis: [
    //"./src/api/v1/routes/v1/index.ts",
    //"./src/api/v1/routes/v1/auth/index.ts",
    //"./src/api/v1/routes/v1/project/index.ts",
    //"./src/api/v1/routes/v1/run/index.ts",
    "./src/api/v1/**/*.ts",
  ],
};

const specs = swaggerJsdoc(options);

function swaggerDoc(app: Express) {
  // app.use(
  //   "/docs",
  //   swaggerUi.serve,
  //   swaggerUi.setup(undefined, {
  //     swaggerOptions: {
  //       url: "/swagger.json",
  //     },
  //   })
  // );
  app.use("/apis", swaggerUi.serve, async (req: Request, res: Response) => {
    //res.send(swaggerUi.setup(specs));
    return res.send(swaggerUi.generateHTML(specs));
  });
  app.get("/swagger.json", (req: Request, res: Response) => {
    res.setHeader("Content-Type", "application/json");
    res.send(specs);
  });
  console.log("Swagger initialized at: " + "/apis");
  console.log("Get swagger docs with: " + "/swagger.json");
}

export { swaggerDoc };
